### ISSUE TITLE
Couple Issues

### ISSUE THREAD

**Issue by Agnet49** [swkeep/keep-hunting#4]
- I installed this and configured it the best I could but I have no ability to slaughter an animal. I am not prompted with any key or anything when I approach an animal

- I am completely clueless on how the /qb-shops/server/main.lua. I have it set up to the best I could with the little knowledge/setup provided.

I also was wondering if there is any way to get rid of these stupid-looking green circles... but keep the markers/radius on the map

![image](https://user-images.githubusercontent.com/100881597/156861493-3f74b1ec-1495-4047-b05c-56af9f6b01eb.png)

![image](https://user-images.githubusercontent.com/100881597/156861499-042cf200-a178-4d0c-bbe8-1a67630fc3e7.png)

![image](https://user-images.githubusercontent.com/100881597/156861638-fdd3133e-78c6-4fc4-9ca7-dea04614b93e.png)

**Comment by swkeep** [comment]
Hi, 

1. to disable green circles just simply change Config.DEBUG = true  to false.
2. your QB-shops/serve/main.lua has duplicate code remove this first
![156861499-042cf200-a178-4d0c-bbe8-1a67630fc3e7](https://user-images.githubusercontent.com/49286776/156876582-e3752fab-05c7-451c-9ca1-3d176460a276.png)
3. make sure your QB-target is updated to the latest version
after all of this If the problem still exists, dm me on Discord.
I probably need your script logs.
