### ISSUE TITLE
Duplicate peds

### ISSUE THREAD

**Issue by ThugE** [swkeep/keep-hunting#7]
For some reason the NPCs are duplicated. I have changed the coords and still seeing the same issue. They overlap each other as can be seen in the pic here. Any help fixing this would be appreciated.
![duplicate](https://user-images.githubusercontent.com/82880556/160274301-4f3c402f-3387-4353-9589-c5b83880980c.JPG)
.

**Comment by swkeep** [comment]
Hi, if i remember correctly it was caused by an outdated qb-target so update it to the latest version.
if it didn't fix the issue we can start debugging.

**Comment by swkeep** [comment]
Hi, it's a little late but may be useful. I found that if any script that has a connection with QB-target has a recent restart and then someone logged out of one of their characters and then login with another one in the same position it will generate duplicate peds.
I will move the hunting shop to QB-shop itself for a better shopping experience.
ty
