### ISSUE TITLE
How-to remove illegal circle zone

### ISSUE THREAD

**Issue by OzumaMR** [swkeep/keep-hunting#8]
I just want the circle zone for legal hunting to show. Leave them look for the illegal one. How would I do that? Thanks!

**Comment by swkeep** [comment]
Hi, to disable the illegal zone entirely just remove the zone from Config.HuntingArea
but if you want to just hide it on the map well it's on the Test branch as an extra field named "showBlip".

**Comment by OzumaMR** [comment]
You a champ. Exactly what I needed. 
A little thing, the hunting shop is called "Rival" for me which is the name of the blip itself.

**Comment by swkeep** [comment]
they were missing showBlip inside their config file.
and I change the script so their names can be changed inside the config file too.

**Comment by OzumaMR** [comment]
Amazing!
One last thing I just encounter is we can't shoot anything not even the spawn animals.

You also need to tell me where to tip you :)

**Comment by swkeep** [comment]
I disabled the shooting protection until when I'm sure it's working as intended!
(you can activate it and give me some feedback it's under "Config.ShootingProtection" )
in my game, this caused some problems within the script.

**Comment by OzumaMR** [comment]
Just tested with true and false and no diff. You can now shoot anyone/everything.

**Comment by swkeep** [comment]
it should only skip other players.

**Comment by OzumaMR** [comment]
Have mine set at:
Config.ShootingProtection = true
Config.ProtectedWeapons = {'weapon_huntingrifle'}
And I can shoot players

**Comment by swkeep** [comment]
Swkeep#7049 this is my discord I might need some debugging data.
